name: SkywarsKillEffects
version: 1.0
main: tk.itsnotalan.swkilleffect.SWKillEffect
commands:
  swkilleffect:
    permission: swke.swke
    aliases: [swke, skywarskilleffects, killeffects]
  rank:
    description: Finished a Season in the Top 10 Leaderboards
    permission: rank.leaderboard_position

permissions:
  swke.swke:
    default: true
  rank.leaderboard_position:
    default: false
